version: "3.8"
services:
  dbmongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin 
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - 27017:27017
    networks:
      - mlsa-net
  api:
    image: racarlosdavid/mlsa_api:v1
    environment:
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: mongo_pass
      MONGO_HOST: dbmongo
    ports:
      - 3000:3000
    networks:
      - mlsa-net
    depends_on:
      - dbmongo
    restart: on-failure
  web:
    image: racarlosdavid/mlsa_app:v1
    ports:
      - 80:80
    networks:
      - mlsa-net
    depends_on:
      - api
    restart: on-failure

networks:
  mlsa-net:
    driver: bridge